name: Web Scraping with Splash

on:
  push:
    branches:
      - main  # Or specify your branch

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my_scraper .

      - name: Run Splash container
        run: docker run -d --name splash_container -p 8050:8050 my_scraper

      - name: Perform scraping
        run: |
          sleep 10  # Wait for container to start (adjust if needed)
          python main.py  # Replace with your script name
        env:
          SPLASH_URL: "http://localhost:8050/render.html"

      - name: Cleanup
        run: docker stop splash_container && docker rm splash_container
